tags:
  dev: true

logging:
  level: debug

public_endpoint_address: endpoint.local
pohttp_tls_required: false

redis:
  host: dev-backing-services-headless

vault:
  host: dev-backing-services-vault
  token: root
