version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    command: src/bin/pohttp-server.ts
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - ./src:/opt/pong-dev/src:ro
    links:
      - redis
    environment:
      REDIS_HOST: redis
      POHTTP_TLS_REQUIRED: 'false'

  queue:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    command: src/bin/background-queue.ts
    volumes:
      - ./src:/opt/pong-dev/src:ro
    links:
      - redis
    environment:
      POHTTP_TLS_REQUIRED: 'false'

      REDIS_HOST: redis

      VAULT_URL: http://vault:8200
      VAULT_TOKEN: letmein
      VAULT_KV_PREFIX: 'session-keys'

      # We should be supporting multiple keys so we can do key rotation.
      # See: https://github.com/relaycorp/relaynet-pong/issues/14
      ENDPOINT_PRIVATE_KEY: ${ENDPOINT_PRIVATE_KEY}

  redis:
    image: redis:5.0-alpine
    init: true

  vault:
    image: vault:1.3.1
    init: true
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: letmein
    cap_add: ["IPC_LOCK"]
    ports:
      - "127.0.0.1:8200:8200"
