version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    command: src/bin/pohttp-server.ts
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./src:/opt/pong-dev/src:ro
    links:
      - redis
    environment:
      REDIS_HOST: redis
      POHTTP_TLS_REQUIRED: 'false'

  queue:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    command: src/bin/background-queue.ts
    volumes:
      - ./src:/opt/pong-dev/src:ro
    links:
      - redis
      - vault
    environment:
      POHTTP_TLS_REQUIRED: 'false'

      REDIS_HOST: redis

      VAULT_URL: http://vault:8200
      VAULT_TOKEN: letmein
      VAULT_KV_PREFIX: 'pong-keys'

      ENDPOINT_KEY_ID: ${ENDPOINT_KEY_ID}

  redis:
    # Use the latest major version supported by GCP Memorystore
    image: redis:5.0.9-alpine
    init: true

  vault:
    image: vault:1.4.2
    init: true
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: letmein
      VAULT_LOG_LEVEL: debug
    cap_add: ["IPC_LOCK"]
    ports:
      - "127.0.0.1:8200:8200"
