version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    command: src/bin/pohttp-server.ts
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./src:/opt/pong-dev/src:ro
    links:
      - redis
    environment:
      APP_VERSION: ${APP_VERSION}

      REDIS_HOST: redis

      POHTTP_TLS_REQUIRED: 'false'

      PUBLIC_ENDPOINT_ADDRESS: ${PUBLIC_ENDPOINT_ADDRESS}

      ENDPOINT_KEY_ID: ${ENDPOINT_KEY_ID}
      ENDPOINT_SESSION_KEY_ID: ${ENDPOINT_SESSION_KEY_ID}

      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: ${VAULT_KV_PREFIX}

  queue:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    command: src/bin/background-queue.ts
    volumes:
      - ./src:/opt/pong-dev/src:ro
    links:
      - redis
      - vault
    environment:
      APP_VERSION: ${APP_VERSION}

      POHTTP_TLS_REQUIRED: 'false'

      REDIS_HOST: redis

      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_KV_PREFIX: ${VAULT_KV_PREFIX}

      ENDPOINT_KEY_ID: ${ENDPOINT_KEY_ID}
      ENDPOINT_SESSION_KEY_ID: ${ENDPOINT_SESSION_KEY_ID}

  redis:
    # Use the latest major version supported by GCP Memorystore
    image: redis:5.0.9-alpine
    init: true

  vault:
    image: vault:1.4.2
    init: true
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_LOG_LEVEL: debug
    cap_add: ["IPC_LOCK"]
    ports:
      - "127.0.0.1:8200:8200"
