FROM node:12.22.7 as build
WORKDIR /tmp/pong-dev
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

FROM node:12.22.7-slim
WORKDIR /opt/pong-dev
COPY --from=build /tmp/pong-dev ./
ENV PATH="/opt/pong-dev/node_modules/.bin:${PATH}"
ENTRYPOINT ["ts-node-dev", "--transpile-only"]
EXPOSE 8080
