version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    command: src/bin/server.ts
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./src:/opt/pong-dev/src
    links:
      - redis

#  queue:
#    build:
#      dockerfile: Dockerfile.dev
#      context: .
#    image: relaynet-pong:local-dev
#    command: app/queue_test.ts
#    volumes:
#      - ./src/app:/opt/pong-dev/app
#    links:
#      - redis
#    environment:
#      REDIS_HOST: redis

  redis:
    image: redis:5.0-alpine
