apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: relaynet-pong
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  helm:
    releases:
    - name: dev-backing-services
      chartPath: chart/dev-backing-services
      valuesFiles:
        - chart/dev-backing-services/values.yml
      wait: true
      skipBuildDependencies: true
    - name: relaynet-pong
      chartPath: chart
      valuesFiles:
      - chart/values.dev.yml
      artifactOverrides:
        image.repository: relaynet-pong
      wait: true
      skipBuildDependencies: true
portForward:
- resourceType: service
  resourceName: dev-backing-services-vault
  port: 8200
  localPort: 8200
- resourceType: service
  resourceName: mock-public-gateway
  port: 80
  localPort: 1080
- resourceType: service
  resourceName: relaynet-pong-pohttp
  port: 80
  localPort: 8080
