apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-generated
data:
  ENDPOINT_KEY_ID: "{{ default (randAscii 12 | b64enc) .Values.current_endpoint_key_id }}"
  ENDPOINT_SESSION_KEY_ID: "{{ default (randAscii 12 | b64enc) .Values.current_endpoint_session_key_id }}"
