apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-generated
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  ENDPOINT_KEY_ID: "{{ default (randAscii 12 | b64enc) .Values.current_endpoint_key_id }}"
  ENDPOINT_SESSION_KEY_ID: "{{ default (randAscii 12 | b64enc) .Values.current_endpoint_session_key_id }}"
