apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}
data:
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: '{{ .Values.redis.port }}'
  POHTTP_TLS_REQUIRED: '{{ .Values.pohttp_tls_required }}'
