apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "..fullname" . }}-keygen
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-keygen"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ include "..fullname" . }}-keygen
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      restartPolicy: OnFailure
      containers:
        - name: keygen
          image: "relaycorp/relaynet-pong:v{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - node
            - build/main/bin/generate-keypairs.js
          env:
            - name: VAULT_URL
              value: "http://{{ .Values.vault.host }}:{{ .Values.vault.port }}"
            - name: VAULT_KV_PREFIX
              value: {{ .Values.vault.session_keys_mount_path }}
          envFrom:
            - configMapRef:
                name: {{ include "..fullname" . }}-generated
            - secretRef:
                name: {{ include "..fullname" . }}-vault
