apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-pohttp
  labels:
    {{- include "..labels" . | nindent 4 }}
    pong.relaycorp.tech/component: pohttp
spec:
  type: {{ .Values.ingress.enabled | ternary "NodePort" .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
    pong.relaycorp.tech/component: pohttp
