version: 2.1
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/src
    steps:
      - test:
          nodeVersion: '10'
  'node-12':
    docker:
      - image: circleci/node:12
    working_directory: ~/src
    steps:
      - test:
          nodeVersion: '12'
  'functional-tests':
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: npm run test:functional

commands:
  test:
    parameters:
      nodeVersion:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-node<< parameters.nodeVersion >>-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node<< parameters.nodeVersion >>-{{ checksum "package.json" }}
      - run: npm run static-checks
      - run: npm run test:ci:unit

workflows:
  version: 2
  build:
    jobs:
      - node-10:
          filters:
            branches:
              ignore:
                - gh-pages
      - node-12:
          filters:
            branches:
              ignore:
                - gh-pages
      - functional-tests
