apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-config-sa
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
