apiVersion: v1
kind: Secret
metadata:
  name: vault-config
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  VAULT_TOKEN: {{ required "Vault token is required" .Values.vault.token | b64enc }}
