apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mock-ce-broker
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
    spec:
      containers:
        - name: mock-ce-broker
          image: mockserver/mockserver:5.15.0
          env:
            - name: MOCKSERVER_SERVER_PORT
              value: '8080'
            - name: MOCKSERVER_LIVENESS_HTTP_GET_PATH
              value: /mockserver/status
          livenessProbe:
            httpGet:
              path: /mockserver/status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /mockserver/status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
            timeoutSeconds: 3
