apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: awala-pong
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
      labels:
        app.kubernetes.io/name: awala-pong
    spec:
      containers:
        - name: awala-pong
          image: dev.local/awala-pong
          env:
            - name: VERSION
              value: 1.0.0
            - name: CE_TRANSPORT
              value: ce-http-binary
            - name: CE_CHANNEL
              value: http://mock-ce-broker.default
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
