export const ENDPOINT_KEY_ID_BASE64 = 'MTM1NzkK';
export const ENDPOINT_SESSION_KEY_ID_BASE64 = 'OTc1MzEK';

export const PUBLIC_ENDPOINT_ADDRESS = 'ping.example.com';

export const ENV_VARS = {
  ENDPOINT_KEY_ID: ENDPOINT_KEY_ID_BASE64,
  ENDPOINT_SESSION_KEY_ID: ENDPOINT_SESSION_KEY_ID_BASE64,
  PUBLIC_ENDPOINT_ADDRESS,
  REDIS_HOST: 'redis.com',
  VAULT_KV_PREFIX: 'pong-keys',
  VAULT_TOKEN: 'root',
  VAULT_URL: 'http://vault.local:8200',
};
