version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_reviewers: [gnarea]
  - package_manager: ruby:bundler
    directory: /docs
    update_schedule: live
    default_reviewers: [gnarea]
