version: '3.7'
services:
  app:
    links:
      - gateway

  gateway:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:local-dev
    init: true
    entrypoint: ''
    command: jest --config jest.config.functional.js
    volumes:
      - .:/opt/pong-dev:ro
    environment:
      POHTTP_TLS_REQUIRED: 'false'
      ENDPOINT_PRIVATE_KEY: ${ENDPOINT_PRIVATE_KEY}
