version: '3.7'
services:
  # Test against the production image
  app:
    build:
      dockerfile: Dockerfile
    image: relaynet-pong:production
    command: ['node', 'build/main/bin/pohttp-server.js']
    links:
      - gateway

  queue:
    build:
      dockerfile: Dockerfile
    image: relaynet-pong:production
    command: ['node', 'build/main/bin/background-queue.js']

  gateway:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: relaynet-pong:development
    init: true
    entrypoint: ''
    command: jest --config jest.config.functional.js
    volumes:
      - .:/opt/pong-dev
      # Use `node_modules` from container; trailing slash is required.
      - /opt/pong-dev/node_modules/
    environment:
      POHTTP_TLS_REQUIRED: 'false'
      ENDPOINT_KEY_ID: ${ENDPOINT_KEY_ID}
