title: Relaynet Pong Service

markdown: kramdown

baseurl: /relaynet-pong
remote_theme: pmarsceill/just-the-docs@v0.2.7-r

footer_content: "Copyright &copy; 2020 Relaycorp, Inc."

search_enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
