name: Run CI and potentially release
on:
  pull_request:
  push:
    branches: [master]
jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-ci.yml@main
    with:
      docker_image_local_name: relaynet-pong
      skaffold_version: 1.35.0

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-server-release.yml@main
    with:
      main_branch: master
    secrets:
      helm_repo_access_token: ${{ secrets.HELM_REPO_ACCESS_TOKEN }}
      ghcr_password: ${{ secrets.GH_CONTAINER_REGISTRY_PASSWORD }}
